services:
  - type: worker  # ← isso é o mais importante!
    name: bot-telegram-planilha
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: ${TOKEN}
